name: chapa_admin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6
  intl: ^0.19.0
  # iconify_flutter: ^0.0.5
  nb_utils: ^6.0.4
  loading_animation_widget: ^1.2.1
  timeago: ^3.6.1
  provider: ^6.1.2
  #Fiirebase
  firebase_core: ^2.24.0
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.6
  cloud_firestore: ^4.13.3
  firebase_auth: ^4.19.5
  firebase_core_platform_interface: ^5.0.0
  equatable: ^2.0.5
  top_snackbar_flutter: ^2.0.0
  # flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  iconly: ^1.0.1
  image: ^4.0.15
  gap: ^3.0.1
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  file_picker: ^8.0.5
  easy_sidemenu: ^0.6.0
  get_it: ^7.7.0
  responsive_builder: ^0.7.0
  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^3.0.1
  rename: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/bulk/
    - assets/icons/linear/
    - assets/icons/twotone/
    - assets/images/
    - assets/

flutter_gen:
  output: lib/generated/
  fonts:
    enabled: false
